### ISSUE TITLE
Minor correct on CIDR address range

### ISSUE THREAD

**Issue by aurrak** [baandab/Synology-Docker-Scripts#1]
Thanks for the scripts! I noticed there could be a minor error on the 2 scripts.

```
#create network shim - see https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/
#
# this creates a subnet (192.168.0.40 to 192.168.0.48) that we can connect to via 192.168.0.49
#
# 192.168.0.49/32 is one address: 192.168.0.49
# 192.168.0.40/29 is a range 192.168.0.40 to 192.168.0.48
# 192.168.0.0/24 is a range 192.168.0.40 to 192.168.0.255
#  
```

192.168.0.40/29 is actually a range of 192.168.0.40 to 192.168.0.47 (according to https://www.ipaddressguide.com/cidr)

So if we were to use the last IP as the shim of the host, I think we should change the --aux-address to 192.168.0.47.

```
/usr/local/bin/docker network create -d macvlan -o parent=eth0 \
  --subnet 192.168.0.0/24 \
  --gateway 192.168.0.1 \
  --ip-range 192.168.0.40/29 \
  --aux-address 'host=192.168.0.47' \
  macvlan1
  
# create shim 
/sbin/ip link add mynet-shim link eth0 type macvlan mode bridge

# add host to shim
/sbin/ip address add 192.168.0.47/32 dev mynet-shim
```

**Comment by aurrak** [comment]
Another minor comment is that when creating the docker `macvlan1` network and creating the network shim, you may need to set the parent interface as `ovs_eth0` instead of `eth0` in case you have Synology Virtual Machine manager installed, and within *its* networking configuration, you have Virtual Network 0 attached to `eth0`.

Source: https://corcoran.medium.com/docker-with-macvlan-networking-on-synology-dsm6-741285a0297d

**Comment by baandab** [comment]
Hi - thanks for the feedback!  

I don't there there is an error with the network range, as the current script works fine for me.  However, I updated the scripts to put the shim address at 192.168.0.49 instead of 192.168.0.48, just in case.

Also, I have updated the scripts with a comment to reflect that the interface might be ovs_eth0:

# change eth0 to ovs_eth0 if you have Synology Virtual Machine manager installed - thanks aurrak!
